# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - '*'
  paths:
    exclude:
    - LICENSE
    - README.md

pr:
  branches:
    include:
    - master
  paths:
    exclude:
    - LICENSE
    - README.md

pool:
  vmImage: 'windows-2019'

steps:
- powershell: |
    $currentVersion = Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion"
    Write-Host "Server version $($currentVersion.BuildLabEx)"
    Write-Host "Server releaseId $($currentVersion.ReleaseId)"
    & docker info 3>$null
  displayName: 'Output environment'
- powershell: .\Build.ps1
  displayName: 'Build image(s)'
